[noit_server]
# Reemplaza con la IP pública de tu instancia EC2
tu-ip-publica ansible_user=ubuntu ansible_ssh_private_key_file=../keys/tu-clave.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no' 